apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-nest-test-cmc
  namespace: lab-cmc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-nest-test-cmc
  template:
    metadata:
      labels:
        app: backend-nest-test-cmc
    spec:
      containers:
      - name: main
        image: us-west1-docker.pkg.dev/lab-agibiz/docker-repository/backend-nest-test-cmc:latest
        ports:
        - containerPort: 3000